### ISSUE TITLE
Question: 金門自來水廠水費

### ISSUE THREAD

**Issue by bluefoxlee** [tsunglung/TpeWaterFee#1]
在準備使用水費時才發現，有一處是在外島。
而如您於電費回覆中提到，查看金門自來水廠的查詢方式與其他公營單位方式類似，因此會先自己試著複製學習改寫看看（程式知識=0）

另請教 不知道是否有使用過 Home Assistant 內建的 Scrape 功能
若僅需要抓取網頁中（約每小時更新一次）某一部分（主要是一項）資料
Beautiful Soup 是不是就顯得太牛刀？
（外島機場天氣會影響飛機起降，因此打算抓取航空氣象中的能見度一欄 來做自動化或通知警告）

**Comment by tsunglung** [comment]
> 在準備使用水費時才發現，有一處是在外島。
> 而如您於電費回覆中提到，查看金門自來水廠的查詢方式與其他公營單位方式類似，因此會先自己試著複製學習改寫看看（程式知識=0）
> 
> 另請教 不知道是否有使用過 Home Assistant 內建的 Scrape 功能
> 若僅需要抓取網頁中（約每小時更新一次）某一部分（主要是一項）資料
> Beautiful Soup 是不是就顯得太牛刀？
> （外島機場天氣會影響飛機起降，因此打算抓取航空氣象中的能見度一欄 來做自動化或通知警告）


寫成 custom_compnemt , 主要是為了簡單易用, 只要會抓 token , 就可以用, 不需去懂怎麼分析網頁

像 Jason 他是自己是用 rest_command 去達到目地
我快速看了一下 scrape , 它無法設定 resquest 的 pyload, 跟 header , 就無法設定 token, 抓取回來網頁, 沒有所需的資訊.
如果是你想自己個人使用, 可以用 RESTful Command 去做
實際怎麼做, 可以問問 Jason.

**Comment by bluefoxlee** [comment]
> 寫成 custom_compnemt , 主要是為了簡單易用, 只要會抓 token , 就可以用, 不需去懂怎麼分析網頁

金水這個優該還是會試著寫成 custom_compnemt 試試看 雖然應該只會有我一個使用者
 
> 像 Jason 他是自己是用 rest_command 去達到目地
> 我快速看了一下 scrape , 它無法設定 resquest 的 pyload, 跟 header , 就無法設定 token, 抓取回來網頁, 沒有所需的資訊.
> 如果是你想自己個人使用, 可以用 RESTful Command 去做
> 實際怎麼做, 可以問問 Jason.

氣象那個 不用Toeken，試過 CSS Selector 配合著去寫 Scrape 還是抓不到資料 要思考看看
來研究一下 RESTful Command 試試看
Jason 是群組內的哪一位呢？貌似沒看到 Jason 大發言？ 不然就上 Dcard 問問
謝謝

**Comment by tsunglung** [comment]
> 金水這個優該還是會試著寫成 custom_compnemt 試試看 雖然應該只會有我一個使用者

你可以先試試, 不行, 我可以幫忙看看
 
> 氣象那個 不用Toeken，試過 CSS Selector 配合著去寫 Scrape 還是抓不到資料 要思考看看

https://aoaws.anws.gov.tw/AWS/index.php
是這個網站?

你可以用 https://aoaws.anws.gov.tw/AWS/mainRight.php?lang=tw&voice_alarm=0&state=Taiwan&icao=RCTP
icao 代表不同的機場

> 來研究一下 RESTful Command 試試看
> Jason 是群組內的哪一位呢？貌似沒看到 Jason 大發言？ 不然就上 Dcard 問問
> 謝謝

他不在那幾個社群裡, 到 dcard 找他, 他比較喜歡用 dcard,

**Comment by tsunglung** [comment]
這是桃園機場的可見度
數字 1 代表欄位桃園機場
數字 14 代表欄位可見度

```sensor:
  - platform: scrape
    resource: "https://aoaws.anws.gov.tw/AWS/mainRight.php?lang=tw&voice_alarm=0&state=Taiwan&icao=RCTP"
    name: RCTP
    scan_interval: 3600
    select: "#select_icao > [language~=JavaScript]"
    value_template: '{{ value.split("addarray(")[1].split(",")[14] }}'```

**Comment by bluefoxlee** [comment]
原來答案早己經貼了，不過寫程式....也太難 Orz
想過從表格去選擇，原來是這樣。感覺路迢迢～

**Comment by bluefoxlee** [comment]
@tsunglung 謝謝協助
